# Extra vatiables for starting up the OGS cluster.

nfs_extra_exports:  # A list of dictionaries that sets the path for extra shared folders on the cluster
  - path: "/exports"
    options: "*(rw,sync,no_subtree_check,no_root_squash)" #options for nfs

ogs_external_submit_hosts: # A list of dictionaries that sets external submit hosts
  - hostname: "galaxy-docker"
    ip_address: "192.168.99.200"
#  - hostname: "another_external_host"
#    ip_address: "10.0.0.20"

ogs_extra_users: # A list of dictionaries that sets users on the cluster with a certain uid.
  - uid: "1450"
    name: "galaxy"
  - uid: "1550"
    name: "postgres"
#ogs_extra_packages: # A list of debian apt packages that will be installed on the cluster
#  - cowsay


# A list of dictionaries that determines which files will be copied from the host system to the vagrant boxes.
# Useful for setting extra configuration files
# Syntax can be found on http://docs.ansible.com/ansible/latest/copy_module.html
# src and dest are compulsory
#ogs_extra_config_files:
#  - src: files/ansible_config
#    dest: /etc/ansible/ansible.cfg
#    mode: "0644" #Octal numbers should always start with a zero and be quoted
#    owner: root
#    group: root
#  - src: files/extra_cow
#    dest: /usr/share/cows/supertux.cow

# A list of services that will be restarted.
# Usefull if configuration files for said services were added
#ogs_extra_services:
#  - docker

# A list of dictionaries that defines which pam modules should be loaded.
# Syntax can be found on http://docs.ansible.com/ansible/latest/pamd_module.html
# Useful if you want to mimick a real cluster's authentication methods
#ogs_pam_modules:
#  - module_path: pam_mkhomedir.so
#    name: common-session
#    control: required
#    type: session
#    module_arguments: "skel=/etc/skel/ umask=0022"
